### ISSUE TITLE
Creacion de Historia de Usuario

### ISSUE THREAD

**Issue by Santidupe** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-04#16]
# Definir la historia de usuario para organizar el repositorio segun requisitos del docente

El scrum master debe crear esta estructura del README.md pero sin agregar ningún integrante, ni cargar datos de ningún tipo, solo la estructura del repositorio según lo indicado por la historia de usuario del PO.

-  Luego debe crear un proyecto Kanban donde agregara las siguientes issues por integrante: 

- [x] Uh#1Tk#1Int_x : Cargar nombre en el readme principal. 

- [ ] Uh#1Tk#2Int_x : Actualizar documentación ESP32 

- [ ] Uh#1Tk#3Int_x : Actualizar Bibliotecas / Recursos 

- Cada integrante debe levantar la issue correspondiente, crear una rama, modificar el repo y generar la pullrequest correspondiente. 

- Comunicarse con el scrum máster para que realice el merge si esta correcto o se desestime.
